[package]
org = "dasit"
name = "e2metrics_task"
version = "0.1.0"
distribution = "2201.8.6"


[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.20"

[build-options]
observabilityIncluded = true
